source 'http://rubygems.org'

gem 'nokogiri', '~> 1.5.10'  # Last version compatible with Ruby 1.9.2
gem 'mini_portile', '~> 0.6.2'
gem 'rails', '3.0.3'
gem 'json_pure',      '1.4.6'
gem 'mysql2'
gem 'jquery-rails'
gem 'haml'
gem 'compass'
gem 'simple_form'
gem 'has_scope'
gem 'devise',         '1.1.3'
gem 'cancan'
gem 'carrierwave',    '0.5.1'
gem 'acts_as_list'
gem 'awesome_nested_set', git: 'git@github.com:collectiveidea/awesome_nested_set.git', branch: '2-1-stable'
gem 'inherited_resources'
gem 'acts-as-taggable-on'
gem 'will_paginate',  '3.0.pre2'
gem 'mini_magick'
gem 'friendly_id',    '3.2.0'
gem 'meta_search'
gem 'rack-ssl-enforcer', '0.2.2'
gem 'RedCloth',       '4.2.3'
gem 'geocoder'
gem 'sanitize'
gem 'rqrcode-rails3'
gem 'truncate_html'
gem 'pdfkit'
gem 'wkhtmltopdf-binary'

group :development, :test do
  gem 'mongrel', '1.2.0.pre2'
#  gem 'webrat'
  gem 'autotest'
 # gem 'capybara'
  gem 'database_cleaner'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'email_spec'
  #gem "spork", :git => "git://github.com/chrismdp/spork.git"
  gem 'launchy'
  gem 'steak'
  gem 'annotate'
  gem 'benhutton-remarkable_activerecord', '>= 4.0.0.alpha6'
  gem 'faker'
  gem 'ruby-debug19'
end
